### ISSUE TITLE
main vs master

### ISSUE THREAD

**Issue by eddycharly** [jmespath-community/go-jmespath#2]
Hi 👋 
I see we have `main` and `master` branches, which one is the _official_ one ?

**Comment by springcomp** [comment]
`main` is the official one.

I actually did not initially delete `master` to [enable my pull requests to be merged by upstream](https://github.com/jmespath/go-jmespath/pulls/springcomp).
Even though I’m not holding my breath. 🤷‍♂️

**Comment by springcomp** [comment]
@eddycharly please, feel free to remove the `master` branch when you want.

**Comment by eddycharly** [comment]
@springcomp not a priority IMHO. When i will have the permissions i will configure ci, linter, etc... to make sure we have enough continuous integration running.

**Comment by springcomp** [comment]
@JimBugwadia @eddycharly welcome to JMESPath Community!

Thanks for offerring to take over maintainance of this repository.

Please let me take this opportunity, for the sake of completeness, to kindly remind you that the underlying assumption is to make all the best effort to stay current on our improvements to the specification?

My goal is to discuss specification improvements in the open as I’ve done for the last year or so.
I just started a [new discussion for brainstorming ideas for the next milestone](https://github.com/jmespath-community/jmespath.spec/discussions/151).
