### ISSUE TITLE
potential bug with `$`

### ISSUE THREAD

**Issue by eddycharly** [jmespath-community/go-jmespath#44]
This unit test should fail I think:
```
	{
		args: args{
			expression: `@."$".a`,
			data: map[string]interface{}{
				"a": 42.0,
			},
		},
		want: 42.0,
	}
```

We are clearly trying to access the `$` field under the current node, but as it doesn't exist we fall back to root node.

cc @springcomp

**Comment by springcomp** [comment]
True.

It should not be mapped to any name at all as all valid string is a valid JSON key.
We should just get it from the scope directly I guess...

The correct result is `null` of course.

Fixing [jmespath.test/issue/#23](https://github.com/jmespath-community/jmespath.test/issues/23) will add a corresponding compliance test.
