### ISSUE TITLE
fix pipe evaluation to multi-select-hash

### ISSUE THREAD

**Issue by springcomp** [jmespath-community/go-jmespath#54]
For consistency, we think both expressions should return their respective results outlines below.

- `` search( `null` | [@] , null ) -> [ null ] `` ✔️
- `` search( `null` | { foo: @ } ) -> null `` ❌

See [jmespath.test/#29](https://github.com/jmespath-community/jmespath.test/issues/29)

**Comment by eddycharly** [comment]
Can you elaborate @springcomp ?

**Comment by springcomp** [comment]
The spec was ambiguous with respect to how `sub-expression` and `pipe-expression` behaved.
Predictably, implementations varied in their behaviours.

We fixed and standardize this with [JEP-19](https://github.com/jmespath-community/jmespath.spec/blob/main/jep-019-pipe-expressions-evaluation.md)

We mentioned some examples in JEP-19:

### Example

| Expression | Result
|---|----
| `` `null` . [@] `` | `null`
| `` `null` \| [@] `` | `[ null ]`

I think for consistency, the last example should be complimented with a corresponding example:

| Expression | Result
|---|----
| `` `null` \| {foo: @} `` | `` {"foo": null } ``

**Comment by eddycharly** [comment]
Thanks I’ll fix it. Do we have compliance tests for that ?

**Comment by springcomp** [comment]
Yes [we do](https://github.com/jmespath-community/jmespath.test/commit/dac8bf8c7a0c83b084fc41f6647c1de5313166db).
