### ISSUE TITLE
Test and fix parser corner cases

### ISSUE THREAD

**Issue by eddycharly** [jmespath-community/go-jmespath#68]
This one for example:

```golang
		args: args{
			expression: "|",
			data: map[string]interface{}{
				"|": 42.0,
			},
		},
		want: 42.0,
```

cc @springcomp

**Comment by springcomp** [comment]
I do not think this is correct.

A property named `|` in a JSON object needs to be   evaluated using a `quoted-identifier`.

So the correct expression would be:

- ` "|" `

**Comment by eddycharly** [comment]
How about `@.|` ? Is this invalid too ?

**Comment by springcomp** [comment]
> How about `@.|` ? Is this invalid too ?

Yes definitely. These are valid as JSON properties and that's why `quoted-identifier` is for.

Even an _unnamed_ property is valid in JSON and must be evaluated by using the empty `quoted-identifier`.

**Comment by eddycharly** [comment]
Ah, good to know, thanks !

**Comment by springcomp** [comment]
FYI, covered by [those tests](https://github.com/jmespath-community/jmespath.test/blob/86fe9102fda76890ef0914b546c1ef821eb6e758/tests/syntax.json#L100).
